apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-api
  template:
    metadata:
      labels:
        app: resume-api
    spec:
      containers:
      - name: resume-api
        image: dozy27/resume-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_PASSWORD
        - name: MONGO_DATABASE
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_DATABASE
      imagePullSecrets:
      - name: dockerhub-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: resume-api   
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  
#---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: api-ingress
# spec:
#   rules:
#   - host: api.yourdomain.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: api-service
#             port:
#               number: 80

