name: Frontend Build and Deploy CI

on:
  push:
    branches:
      - 'main'

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get repo
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./resume-ui/Dockerfile
          push: true
          tags: dozy27/resume-ui:latest
          
  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - 
        name: Check out code
        uses: actions/checkout@v3

      - 
        name: Set up kubeconfig
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - 
        name: Connect to Kubernetes cluster
        run: |
          echo "$KUBECONFIG_FILE" > kubeconfig.yml
          export KUBECONFIG=kubeconfig.yml

      - 
        name: Deploy API
        run: |
          envsubst < k8s/ui-deployment-template.yml > deployment.yml
          kubectl apply -f deployment.yml
